In [68]:
import pandas as pd

df = pd.read_csv("ecommerce_reviews.csv")
df.head(5)

,Review_ID,Product_Name,Category,Brand,Price,Rating,Review_Text,Review_Date,Verified_Purchase,Helpful_Votes,Review_Length,Discount_Percentage
0,1,PS5,Gaming,Samsung,37206.75,3,It's decent. Nothing special but works fine. C...,2023-04-15,True,456,106,50
1,2,Refrigerator,Electronics,Lenovo,2073.24,2,Broken on arrival. Very upset. But course act ...,2024-06-01,True,287,79,15
2,3,Gaming Headset,Gaming,Lenovo,11411.81,4,Amazing product! Exceeded my expectations. Hig...,2023-06-13,True,174,154,20
3,4,iPhone 13,Smartphones,HP,5559.41,4,Superb product. Great customer service too. Va...,2023-12-19,True,413,124,0
4,5,Mechanical Keyboard,Gaming,OnePlus,6678.90,5,Great quality and fast delivery. Very satisfie...,2023-10-28,True,316,96,25

In [69]:
print("Total Rows In The Dataset:",df.shape[0])
print("Total Columns In The Dataset:",df.shape[1],"\n")

print("Columns Names: ",df.columns,"\n")

print(f"Date Range: {df['Review_Date'].min()} to {df['Review_Date'].max()}")

Total Rows In The Dataset: 2500
Total Columns In The Dataset: 12

Columns Names:  Index(['Review_ID', 'Product_Name', 'Category', 'Brand', 'Price', 'Rating',
       'Review_Text', 'Review_Date', 'Verified_Purchase', 'Helpful_Votes',
       'Review_Length', 'Discount_Percentage'],
      dtype='object')

Date Range: 2023-01-01 to 2024-07-04

In [ ]:
print("Missing Values In The Dataset:")
print(df.isnull().sum())

Missing Values In The Dataset:

Review_ID              0
Product_Name           0
Category               0
Brand                  0
Price                  0
Rating                 0
Review_Text            0
Review_Date            0
Verified_Purchase      0
Helpful_Votes          0
Review_Length          0
Discount_Percentage    0
dtype: int64

In [71]:
print("Data Info:")
print(df.info())

Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Review_ID            2500 non-null   int64
 1   Product_Name         2500 non-null   object
 2   Category             2500 non-null   object
 3   Brand                2500 non-null   object
 4   Price                2500 non-null   float64
 5   Rating               2500 non-null   int64
 6   Review_Text          2500 non-null   object
 7   Review_Date          2500 non-null   object
 8   Verified_Purchase    2500 non-null   bool
 9   Helpful_Votes        2500 non-null   int64
 10  Review_Length        2500 non-null   int64
 11  Discount_Percentage  2500 non-null   int64
dtypes: bool(1), float64(1), int64(5), object(5)
memory usage: 217.4+ KB
None

In [72]:
print("Unique Values:")
print(df.nunique())

Unique Values:
Review_ID              2500
Product_Name             35
Category                  7
Brand                    10
Price                  2500
Rating                    5
Review_Text            2500
Review_Date             544
Verified_Purchase         2
Helpful_Votes           494
Review_Length           101
Discount_Percentage       9
dtype: int64

In [73]:
print("Statitics:")
df.describe()

Statitics:

,Review_ID,Price,Rating,Helpful_Votes,Review_Length,Discount_Percentage
count,2500.00000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000
mean,1250.50000,25023.885132,3.861600,219.758000,107.716400,21.544000
std,721.83216,14367.801985,1.117025,151.282098,19.274184,15.301952
min,1.00000,533.830000,1.000000,0.000000,58.000000,0.000000
25%,625.75000,12493.525000,3.000000,77.000000,94.000000,10.000000
50%,1250.50000,25256.485000,4.000000,205.000000,107.000000,20.000000
75%,1875.25000,37594.215000,5.000000,356.000000,121.000000,30.000000
max,2500.00000,49991.150000,5.000000,500.000000,162.000000,50.000000

In [74]:
print(f"Price Range: ₹{df['Price'].min():.2f} - ₹{df['Price'].max():.2f}")
print(f"Average Price: ₹{df['Price'].mean():.2f}")

Price Range: ₹533.83 - ₹49991.15
Average Price: ₹25023.89

In [75]:
print("Brand Distribution:")
print(df['Brand'].value_counts())

Brand Distribution:
Brand
OnePlus    271
Lenovo     264
Asus       263
HP         262
LG         253
Apple      247
Samsung    245
Sony       243
Dell       235
Xiaomi     217
Name: count, dtype: int64

In [76]:
print("Category Distribution:")
print(df['Category'].value_counts())

Category Distribution:
Category
Smart Home     372
Smartphones    365
Electronics    365
Accessories    357
Gaming         350
Tablets        350
Laptops        341
Name: count, dtype: int64

In [77]:
print("Rating Distribution:")
print(df['Rating'].value_counts().sort_index())

Rating Distribution:
Rating
1    101
2    256
3    382
4    910
5    851
Name: count, dtype: int64

In [78]:
print("Verified Purchase Distribution:")
print(df["Verified_Purchase"].value_counts())

Verified Purchase Distribution:
Verified_Purchase
True     2112
False     388
Name: count, dtype: int64